main.yml
name: Test Action

on:
push:
branches:

jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: 23f3002023@ds.study.iitm.ac.in
         run: echo "Hello, world!"
